[datasets][m]:- created core datasets page - refs #41
frictionlessdata/dpr-docs pull request #42
Opened 2017-05-24 15:31 UTC by Mikanebu

Create core-datasets page with introduction and full tutorial.

2017-05-24 17:24 UTC, anuveyatsu commented on docs/publishers/core-datasets.md
> +**Core Datasets** - important, commonly-used datasets in high quality, easy-to-use & open form.
I'm not sure if "commonly-used" is a compound word.

2017-05-24 17:27 UTC, anuveyatsu commented on docs/publishers/core-datasets.md
> +**High Quality & Reliable** - sourcing, normalizing and quality checking a set of **key reference and indicator datasets such as country codes, currencies, GDP and population**
We've never discussed it, but should we use standard (British) English or American English? For instance, here we have "normalizing", which is spelt in American.

2017-05-24 17:33 UTC, anuveyatsu commented on docs/publishers/core-datasets.md
> +Each of these have sub-steps which we detail below and you can contribute in any and all of these. [In fact given how many of us there are you will almost end up doing several of these at once!]
Each of these **have** => **has**

2017-05-24 17:34 UTC, anuveyatsu commented on docs/publishers/core-datasets.md
> +* Discuss with Queue Manager(s) (they will spot your submission and start commenting in the github issue)
Very minor but we normally write "GitHub" instead of "github".

2017-05-24 17:35 UTC, anuveyatsu commented on docs/publishers/core-datasets.md
> +* All Data Packages must (ultimately) be stored in a public github repo
Same for "GitHub"

2017-05-24 17:37 UTC, anuveyatsu requested changes
Small suggestions on spelling

2017-05-25 04:32 UTC, Mikanebu commented on docs/publishers/core-datasets.md
> +**High Quality & Reliable** - sourcing, normalizing and quality checking a set of **key reference and indicator datasets such as country codes, currencies, GDP and population**
This info is taken from http://data.okfn.org/roadmap/core-datasets. Either we can keep it or change it in their main page. Personally, I think, we can keep it as a 'normalizing'

2017-05-25 04:32 UTC, Mikanebu commented on docs/publishers/core-datasets.md
> +Each of these have sub-steps which we detail below and you can contribute in any and all of these. [In fact given how many of us there are you will almost end up doing several of these at once!]
Good point

2017-05-25 04:35 UTC, Mikanebu commented on docs/publishers/core-datasets.md
> +**Core Datasets** - important, commonly-used datasets in high quality, easy-to-use & open form.
I did some research using google Ngram Viewer, so "commonly used" would be better to use.
https://books.google.com/ngrams/graph?content=commonly+used%2Ccommonly-used&year_start=1900&year_end=2000&corpus=18&smoothing=3&share=&direct_url=t1%3B%2Ccommonly%20used%3B%2Cc0%3B.t1%3B%2Ccommonly%20-%20used%3B%2Cc0.

2017-05-25 04:35 UTC, Mikanebu commented on docs/publishers/core-datasets.md
> +* Discuss with Queue Manager(s) (they will spot your submission and start commenting in the github issue)
done

2017-05-25 04:36 UTC, Mikanebu commented on docs/publishers/core-datasets.md
> +* All Data Packages must (ultimately) be stored in a public github repo
done

2017-05-25 07:34 UTC, anuveyatsu approved these changes

2017-05-25 07:34 UTC, merged